pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 -v ~/npmartifacts:/var/lib/jenkins/'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                withNPM(npmrcConfig: '~/npmartifacts/.npmrc') {
                    //sh './jenkins/scripts/deliver.sh'
                    pwd & npm config ls -l
                }
                //input message: 'Finished using the web site? (Click "Proceed" to continue)'
                //sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
